name: Pipeline
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install poetry
        run: pipx install poetry
      - name: Install dependencies
        run: poetry install
      - name: Execute tests
        run: poetry run task test

